### ISSUE TITLE
[homeassistant.components.mqtt.climate] temperature parse error

### ISSUE THREAD

**Issue by shinyone** [gysmo38/mitsubishi2MQTT#141]
Hi, I'm using this module with home assistant integration.  However, I'm not sure where the problem is coming from.

If any of the units is set to the lower temp (16 degrees C) then the following error is shown in the logs.

`ERROR (MainThread) [homeassistant.components.mqtt.climate] Could not parse temperature from `

Here the required temp is set to 17.  And the slider is in position "1"
![image](https://user-images.githubusercontent.com/41118905/120599672-18575c80-c448-11eb-9716-9eb3a142af0d.png)

I can move the slider via the HA dashboard to 16 (position "0"), but using the remote to reduce the temp, causes the error above.

The workaround is to manualy move the slider (or not use the lowest temp).    

But where / what is the problem?

**Comment by adipierro** [comment]
I have experienced the same. The reason is Home Assistant assuming temperature will be higher than min_value, which is 16° (and lower than max_value, which is 31°) and if it equals, it fails to parse MQTT message. Sadly, don’t know if it is expected behavior or a bug. We probably should ask Home Assistant developers…

**Comment by shinyone** [comment]
OK, Thanks for your comment, I will close this bug here then.
