### ISSUE TITLE
Seems like this project is dead - here's another option

### ISSUE THREAD

**Issue by adamderuwe** [gysmo38/mitsubishi2MQTT#151]
The repo owner seems to have abandoned this project.  If you are willing to use ESPHome, this looks to be a good option:

https://github.com/geoffdavis/esphome-mitsubishiheatpump

**Comment by ostat** [comment]
It does currently seem that way. There are quite a few people who have been out there making changes on their own forks. I wonder if anyone else would be prepared to take over at least until @gysmo38 returns?

with regards to the esp home solution, are you able to explain the pros and cons of switching?

**Comment by zkniebel** [comment]
Not sure why you would switch. Are you having trouble getting it working? This project is fully working for me. You can use my fork if you want, just note that I included an enhanced version of heatpump with a couple of fixes that I found for issues I was having with setting the remote temp. It was just two small fixes so I was lazy and just included them in the same repo rather than making a separate one (if you search for "ZK:" you'll see each change with a comment for each).

There's a pretty active Discord for SwiCago and the heatpump project in general and a lot of people seem to use this project. I was able to get it working with minimal hiccups thanks to their help. If you have questions, I would hop over there, in addition to logging a ticket here.

**Comment by ghost** [comment]
So is there a process to change ownership or do we collectively just vote and use some other fork?

**Comment by gysmo38** [comment]
I was pretty busy on others projects but I will try to me more active on it. I use it without any issue, that is also why I am not very active on it. I merge last PR and will be more reactive for others :)

**Comment by gysmo38** [comment]
I will try to follow PR and this project. Open a new one issue if needed :p
