### ISSUE TITLE
Humidity Reporting

### ISSUE THREAD

**Issue by heffneil** [gysmo38/mitsubishi2MQTT#180]
Is there a way to add Humidity reporting to the MQTT server?  This data would be useful to have?

**Comment by melyux** [comment]
I think that's a change that would have to be made in SwiCago/HeatPump because this project relies on that library to interact with the Mitsubishi. I don't think HeatPump has support for humidity. Do any Mitsubishi heat pumps/mini splits even report humidity?

Or maybe you mean adding a humidity sensor to the ESP itself and reporting that on the side?

**Comment by gysmo38** [comment]
Units do not report humidity
